-- Auto-generated migration: Please do not edit this file directly. 

CREATE TABLE IF NOT EXISTS metrics_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp DATETIME NOT NULL,
    messages_per_sec REAL NOT NULL,
    active_channels INTEGER NOT NULL,
    total_users INTEGER NOT NULL,
    sentiment_score REAL NOT NULL,
    trading_pnl REAL NOT NULL,
    ai_response_time REAL NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_metrics_timestamp ON metrics_history(timestamp);
