controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "mpc_controller::MPCController"

planner_server:
  ros__parameters:
    planner_plugins: ["SBPLPlanner", "OMPLPlanner"]
    SBPLPlanner:
      plugin: "nav2_sbpl_planner/SBPLPlanner"
    OMPLPlanner:
      plugin: "ompl_planner/OMPLPlanner"

bt_navigator:
  ros__parameters:
    bt_loop_duration: 10
    default_server_timeout: 20
    bt_xml_file: "/opt/pirc-navigation/behavior_trees/bt_library.xml"
